# Generated by Django 5.2.10 on 2026-02-05 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("learning", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningsession",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursesection",
            ),
        ),
    ]
