# Generated by Django 5.2.10 on 2026-02-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_alter_learningsession_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningsession",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="유튜브 학습 시 영상 URL",
                max_length=500,
                null=True,
            ),
        ),
    ]
