# Generated by Django 5.2.10 on 2026-02-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_lecture_learningsession_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="access_code",
            field=models.CharField(
                blank=True, help_text="수강생 입장 코드", max_length=6, unique=True
            ),
        ),
    ]
