# Generated by Django 5.2.10 on 2026-02-07 04:56

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("learning", "0006_lecture_access_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyquiz",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursesection",
            ),
        ),
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="원본 텍스트 청크")),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        dimensions=1536,
                        help_text="OpenAI text-embedding-3-small (1536 dim)",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        default="stt", help_text="stt, summary, material", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vectors",
                        to="learning.lecture",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vectors",
                        to="learning.learningsession",
                    ),
                ),
            ],
        ),
    ]
