# Generated by Django 5.2.10 on 2026-02-07 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_alter_dailyquiz_section_vectorstore"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningsession",
            name="context_summary",
            field=models.TextField(
                blank=True, help_text="현재까지의 대화/자막 압축 요약본", null=True
            ),
        ),
        migrations.AddField(
            model_name="learningsession",
            name="last_compressed_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="마지막 압축 시점"
            ),
        ),
    ]
