# Generated by Django 4.2.28 on 2026-02-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_syllabus_learningobjective_studentchecklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="review_note",
            field=models.TextField(blank=True, help_text="AI 오답노트 및 학습 가이드"),
        ),
    ]
