# Generated by Django 5.2.10 on 2026-02-20 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0010_quizattempt_review_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordingUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audio_file", models.FileField(upload_to="recordings/%Y/%m/")),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="바이트 단위"),
                ),
                (
                    "duration_seconds",
                    models.IntegerField(
                        blank=True, help_text="오디오 길이(초)", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기 중"),
                            ("SPLITTING", "오디오 분할 중"),
                            ("TRANSCRIBING", "STT 변환 중"),
                            ("SUMMARIZING", "요약 생성 중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, help_text="처리 진행률 0~100"),
                ),
                (
                    "total_chunks",
                    models.IntegerField(default=0, help_text="분할된 총 청크 수"),
                ),
                (
                    "processed_chunks",
                    models.IntegerField(default=0, help_text="처리 완료된 청크 수"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="learning.lecture",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="처리 완료 후 연결되는 학습 세션",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.learningsession",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
