# Generated by Django 5.2.10 on 2026-02-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0011_recording_upload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="교안 제목", max_length=200)),
                ("file", models.FileField(upload_to="materials/%Y/%m/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("PPT", "PowerPoint"),
                            ("MD", "마크다운"),
                            ("OTHER", "기타"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="learning.lecture",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="세션 제목 (예: Week 3 - Django ORM)",
                        max_length=200,
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        blank=True,
                        help_text="학생 입장용 6자리 코드",
                        max_length=6,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "대기 중"),
                            ("LIVE", "진행 중"),
                            ("ENDED", "종료됨"),
                        ],
                        default="WAITING",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_live_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_sessions",
                        to="learning.lecture",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveSTTLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_order", models.IntegerField()),
                ("text_chunk", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stt_logs",
                        to="learning.livesession",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence_order"],
            },
        ),
        migrations.CreateModel(
            name="LiveParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="현재 접속 중 여부 (heartbeat 기반)"
                    ),
                ),
                (
                    "last_heartbeat",
                    models.DateTimeField(auto_now=True, help_text="마지막 활동 시간"),
                ),
                (
                    "learning_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="입장 시 자동 생성되는 개인 학습 세션",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.learningsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="learning.livesession",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
                "unique_together": {("live_session", "student")},
            },
        ),
    ]
