# Generated by Django 4.2.28 on 2026-02-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_recording_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='sttlog',
            name='end_time',
            field=models.FloatField(blank=True, help_text='자막 종료 시간 (초)', null=True),
        ),
        migrations.AddField(
            model_name='sttlog',
            name='start_time',
            field=models.FloatField(blank=True, help_text='자막 시작 시간 (초)', null=True),
        ),
    ]
