# Generated by Django 4.2.28 on 2026-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_sttlog_end_time_sttlog_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='is_analyzing',
            field=models.BooleanField(default=False),
        ),
    ]
