# Generated by Django 4.2.28 on 2026-02-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0013_learningsession_is_analyzing'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='ai_status',
            field=models.CharField(default='pending', help_text='AI 처리 상태', max_length=50),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='script_segments',
            field=models.JSONField(default=list, help_text='자막 세그먼트 데이터'),
        ),
    ]
