# Generated by Django 5.2.10 on 2026-02-20 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0013_pulsecheck"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(help_text="퀴즈 문제")),
                (
                    "options",
                    models.JSONField(
                        help_text="객관식 보기 리스트 (예: ['A답', 'B답', 'C답', 'D답'])"
                    ),
                ),
                ("correct_answer", models.CharField(help_text="정답", max_length=255)),
                ("explanation", models.TextField(blank=True, help_text="해설")),
                ("is_ai_generated", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="현재 활성 퀴즈 여부"),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="learning.livesession",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.CreateModel(
            name="LiveQuizResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField()),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="learning.livequiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_quiz_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("quiz", "student")},
            },
        ),
    ]
