# Generated by Django 5.2.10 on 2026-02-20 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0014_livequiz_livequizresponse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "ai_answer",
                    models.TextField(blank=True, help_text="RAG AI가 즉시 생성한 답변"),
                ),
                (
                    "instructor_answer",
                    models.TextField(
                        blank=True, help_text="교수자가 수동으로 작성한 답변"
                    ),
                ),
                (
                    "upvotes",
                    models.IntegerField(default=0, help_text="다른 학생들의 공감 수"),
                ),
                (
                    "cluster_id",
                    models.IntegerField(
                        blank=True, help_text="유사 질문 그룹 ID", null=True
                    ),
                ),
                (
                    "is_answered",
                    models.BooleanField(
                        default=False, help_text="교수자가 답변 완료 여부"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.livesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-upvotes", "-created_at"],
            },
        ),
    ]
