# Generated by Django 5.2.10 on 2026-02-20 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0015_livequestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveSessionNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="AI 생성 통합 노트 (Markdown)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "생성 중"),
                            ("DONE", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        default=dict, help_text="세션 통계 (참가자수, 정답률 등)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note",
                        to="learning.livesession",
                    ),
                ),
            ],
        ),
    ]
