# Generated by Django 5.2.10 on 2026-02-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0016_livesessionnote"),
    ]

    operations = [
        migrations.AddField(
            model_name="livequiz",
            name="time_limit",
            field=models.IntegerField(default=60, help_text="제한 시간 (초)"),
        ),
    ]
