# Generated by Django 5.2.10 on 2026-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0017_livequiz_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="livequiz",
            name="is_suggestion",
            field=models.BooleanField(
                default=False, help_text="AI 자동 제안 (교수자 미승인)"
            ),
        ),
    ]
