# Generated by Django 5.2.10 on 2026-02-20 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0018_livequiz_is_suggestion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(help_text="문제 내용")),
                (
                    "options",
                    models.JSONField(
                        help_text="보기 리스트 (예: ['A답', 'B답', 'C답', 'D답'])"
                    ),
                ),
                ("correct_answer", models.CharField(help_text="정답", max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONCEPT", "개념 이해도"),
                            ("PRACTICE", "실습 경험"),
                            ("PATTERN", "학습 패턴"),
                        ],
                        default="CONCEPT",
                        max_length=20,
                    ),
                ),
                ("difficulty", models.IntegerField(default=1, help_text="난이도 1~3")),
                ("order", models.IntegerField(default=0, help_text="출제 순서")),
                ("explanation", models.TextField(blank=True, help_text="정답 해설")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="역량 이름 (예: 클로저 이해)", max_length=100
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("JAVASCRIPT", "JavaScript"),
                            ("PYTHON", "Python"),
                            ("HTML_CSS", "HTML/CSS"),
                            ("FRAMEWORK", "Framework"),
                            ("DATABASE", "Database"),
                            ("DEVOPS", "DevOps"),
                            ("CS_BASIC", "CS 기초"),
                            ("SOFT_SKILL", "소프트스킬"),
                        ],
                        default="JAVASCRIPT",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="역량 상세 설명"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        default=1, help_text="난이도 (1=기초, 2=중급, 3=심화)"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="표시 순서")),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="PlacementResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1: 완전 초보"),
                            (2, "Level 2: 기초 이해자"),
                            (3, "Level 3: 실습 경험자"),
                        ],
                        default=1,
                    ),
                ),
                ("score", models.IntegerField(default=0, help_text="총 맞은 개수")),
                ("total_questions", models.IntegerField(default=20)),
                (
                    "answers",
                    models.JSONField(
                        default=dict,
                        help_text="응답 기록 {question_id: selected_answer}",
                    ),
                ),
                (
                    "category_scores",
                    models.JSONField(
                        default=dict,
                        help_text="카테고리별 점수 {CONCEPT: 5, PRACTICE: 3, PATTERN: 2}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_results",
                        to="learning.lecture",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareerGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="직무명 (예: 프론트엔드 개발자)", max_length=100
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="직무 설명")),
                (
                    "estimated_weeks",
                    models.IntegerField(default=12, help_text="예상 학습 기간 (주)"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="💻", help_text="아이콘 이모지", max_length=10
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True, related_name="career_goals", to="learning.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="StudentGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_goal_text",
                    models.TextField(blank=True, help_text="직접 입력한 목표 (선택)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "career_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="learning.careergoal",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OWNED", "보유 ✅"),
                            ("GAP", "미보유 🔲"),
                            ("LEARNING", "학습 중 🔄"),
                        ],
                        default="GAP",
                        max_length=10,
                    ),
                ),
                ("progress", models.IntegerField(default=0, help_text="숙달도 0~100%")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_records",
                        to="learning.skill",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["skill__category", "skill__order"],
                "unique_together": {("student", "skill")},
            },
        ),
    ]
