# Generated by Django 5.2.10 on 2026-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0019_placementquestion_skill_placementresult_careergoal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="livesessionnote",
            name="instructor_insight",
            field=models.TextField(
                blank=True, help_text="교수자용 인사이트 리포트 (Markdown)"
            ),
        ),
    ]
