# Generated by Django 5.2.10 on 2026-02-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0020_livesessionnote_instructor_insight"),
    ]

    operations = [
        migrations.AddField(
            model_name="livesessionnote",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="livesessionnote",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="교수자 승인 여부 (True=학생 공개)"
            ),
        ),
        migrations.AddField(
            model_name="livesessionnote",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="결석생 포함 전체 공개 여부"
            ),
        ),
        migrations.AddField(
            model_name="livesessionnote",
            name="linked_materials",
            field=models.ManyToManyField(
                blank=True,
                help_text="세션에 연결된 교안",
                related_name="linked_notes",
                to="learning.lecturematerial",
            ),
        ),
    ]
