# Generated by Django 5.2.10 on 2026-02-20 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0022_pulselog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeakZoneAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("QUIZ_WRONG", "퀴즈 오답"),
                            ("PULSE_CONFUSED", "연속 혼란 펄스"),
                            ("COMBINED", "복합 (오답+혼란)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_detail",
                    models.JSONField(
                        default=dict,
                        help_text="트리거 상세 { quiz_ids, confused_count, recent_topic }",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DETECTED", "감지됨"),
                            ("MATERIAL_PUSHED", "보충 자료 전송됨"),
                            ("DISMISSED", "교수자 거부"),
                            ("RESOLVED", "학생 확인"),
                        ],
                        default="DETECTED",
                        max_length=20,
                    ),
                ),
                (
                    "ai_suggested_content",
                    models.TextField(blank=True, help_text="AI가 생성한 보충 설명"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_zones",
                        to="learning.livesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weak_zone_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplement_material",
                    models.ForeignKey(
                        blank=True,
                        help_text="교수자가 푸시한 보충 자료",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.lecturematerial",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
