# Generated by Django 5.2.10 on 2026-02-20 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0023_weakzonealert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpacedRepetitionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concept_name",
                    models.CharField(help_text="복습 개념명", max_length=200),
                ),
                ("review_question", models.TextField(help_text="빠른 확인용 1문항")),
                ("review_answer", models.CharField(max_length=500)),
                (
                    "review_options",
                    models.JSONField(default=list, help_text="4지선다 보기"),
                ),
                (
                    "schedule",
                    models.JSONField(
                        default=list,
                        help_text="5주기 스케줄 [{ review_num, label, due_at, completed }]",
                    ),
                ),
                (
                    "current_review",
                    models.IntegerField(
                        default=0, help_text="현재 몇 차 복습까지 완료"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.livequiz",
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spaced_items",
                        to="learning.livesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spaced_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        default=list,
                        help_text="복습 항목 [{ order, type, title, content/note_id, est_minutes }]",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUGGESTED", "AI 제안"),
                            ("AUTO_APPROVED", "자동 승인"),
                            ("APPROVED", "교수자 수동 승인"),
                            ("MODIFIED", "교수자 수정"),
                            ("REJECTED", "교수자 거부"),
                        ],
                        default="AUTO_APPROVED",
                        max_length=20,
                    ),
                ),
                ("total_est_minutes", models.IntegerField(default=0)),
                (
                    "completed_items",
                    models.JSONField(
                        default=list, help_text="완료된 order 목록 [1, 2, ...]"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_routes",
                        to="learning.livesession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("live_session", "student")},
            },
        ),
    ]
