# Generated by Django 5.2.10 on 2026-02-20 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0024_spacedrepetitionitem_reviewroute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FormativeAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        default=list,
                        help_text='\n    [{\n        "id": 1,\n        "question": "클로저란 무엇인가?",\n        "options": ["A", "B", "C", "D"],\n        "correct_answer": "B",\n        "explanation": "...",\n        "related_note_section": "## 핵심 내용 정리 > 1. 클로저",\n        "concept_tag": "클로저"\n    }]\n    ',
                    ),
                ),
                ("total_questions", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "생성 중"),
                            ("READY", "준비 완료"),
                            ("FAILED", "생성 실패"),
                        ],
                        default="GENERATING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "live_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formative_assessments",
                        to="learning.livesession",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formative_assessments",
                        to="learning.livesessionnote",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormativeResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        default=list, help_text="[{ question_id, answer, is_correct }]"
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                (
                    "sr_items_created",
                    models.BooleanField(
                        default=False, help_text="오답→SR 자동 등록 완료 여부"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="learning.formativeassessment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formative_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "unique_together": {("assessment", "student")},
            },
        ),
    ]
