# Generated by Django 5.2.10 on 2026-02-20 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0025_formativeassessment_formativeresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdaptiveContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1 - 기초"),
                            (2, "Level 2 - 표준"),
                            (3, "Level 3 - 심화"),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(help_text="AI 변형 마크다운")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATING", "AI 생성 중"),
                            ("DRAFT", "AI 생성 초안"),
                            ("APPROVED", "교수자 승인"),
                            ("REJECTED", "교수자 거부"),
                        ],
                        default="GENERATING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptive_contents",
                        to="learning.lecturematerial",
                    ),
                ),
            ],
            options={
                "ordering": ["level"],
                "unique_together": {("source_material", "level")},
            },
        ),
    ]
