# Generated by Django 5.2.10 on 2026-02-20 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0026_adaptivecontent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_level",
                    models.IntegerField(
                        choices=[
                            (0, "전체"),
                            (1, "Level 1"),
                            (2, "Level 2"),
                            (3, "Level 3"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "target_students",
                    models.JSONField(
                        default=list,
                        help_text="특정 학생 ID 목록 (빈 리스트면 레벨 기준)",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("NOTICE", "공지"),
                            ("TASK", "추가 과제"),
                            ("FEEDBACK", "1:1 피드백 요청"),
                            ("SUPPLEMENT", "보충 자료"),
                        ],
                        default="NOTICE",
                        max_length=20,
                    ),
                ),
                (
                    "read_by",
                    models.JSONField(default=list, help_text="읽은 학생 ID 목록"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_messages",
                        to="learning.lecture",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoteViewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="learning.livesessionnote",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("note", "student")},
            },
        ),
    ]
