# Generated by Django 5.2.10 on 2026-02-20 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0027_groupmessage_noteviewlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="획득 시점 레벨 (1=Beginner/씨앗, 2=Intermediate/새싹, 3=Advanced/꽃)",
                    ),
                ),
                (
                    "checkpoint_score",
                    models.FloatField(default=0, help_text="체크포인트 통과율 (0~100)"),
                ),
                (
                    "formative_score",
                    models.FloatField(default=0, help_text="형성평가 점수 (0~100)"),
                ),
                (
                    "understand_score",
                    models.FloatField(default=0, help_text="펄스 이해도 비율 (0~100)"),
                ),
                (
                    "total_score",
                    models.FloatField(default=0, help_text="종합 점수 (가중 평균)"),
                ),
                (
                    "is_earned",
                    models.BooleanField(default=False, help_text="블록 획득 여부"),
                ),
                ("earned_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_blocks",
                        to="learning.lecture",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="learning.skill",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_blocks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["skill__category", "skill__order"],
                "unique_together": {("student", "skill", "lecture")},
            },
        ),
    ]
