# Generated by Django 5.2.10 on 2026-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0028_skillblock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adaptivecontent",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1 - 초등"),
                    (2, "Level 2 - 중등"),
                    (3, "Level 3 - 성인"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="lecturematerial",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF"),
                    ("PPT", "PowerPoint"),
                    ("DOCX", "Word 문서"),
                    ("MD", "마크다운"),
                    ("TXT", "텍스트"),
                    ("HWP", "한글 문서"),
                    ("OTHER", "기타"),
                ],
                default="PDF",
                max_length=10,
            ),
        ),
    ]
