# Generated by Django 5.2.10 on 2026-02-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0029_add_docx_txt_hwp_file_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="end_date",
            field=models.DateField(blank=True, help_text="종강일", null=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="start_date",
            field=models.DateField(blank=True, help_text="첫 강의일", null=True),
        ),
        migrations.AlterField(
            model_name="adaptivecontent",
            name="level",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1 - 쉽게 이해하기"),
                    (2, "Level 2 - 핵심 정리"),
                    (3, "Level 3 - 심화 완성"),
                ]
            ),
        ),
    ]
