# Generated by Django 5.2.10 on 2026-02-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0030_lecture_end_date_lecture_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturematerial",
            name="content_data",
            field=models.TextField(
                blank=True, default="", help_text="URL 주소 또는 마크다운 텍스트 원본"
            ),
        ),
        migrations.AddField(
            model_name="lecturematerial",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("FILE", "파일 업로드"),
                    ("LINK", "외부 링크"),
                    ("MARKDOWN", "마크다운 텍스트"),
                ],
                default="FILE",
                help_text="자료 유형 (FILE, LINK, MARKDOWN)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lecturematerial",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="파일 업로드 (FILE 타입일 때 사용)",
                null=True,
                upload_to="materials/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="lecturematerial",
            name="title",
            field=models.CharField(help_text="자료 제목", max_length=200),
        ),
    ]
