# Generated by Django 5.2.10 on 2026-02-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0031_add_content_fields_to_lecturematerial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturematerial",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                help_text="NULL이면 공통 기초 자료",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="learning.lecture",
            ),
        ),
    ]
