# Generated by Django 5.2.10 on 2026-02-24 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0032_make_lecture_nullable_in_lecturematerial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="세션 제목 (첫 질문에서 자동 생성)",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="세션 활성 여부"),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        help_text="질문 문맥 (어느 강의에서 질문했는지)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="learning.lecture",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[
                            ("USER", "학생"),
                            ("AI", "AI 튜터"),
                            ("SYSTEM", "시스템"),
                        ],
                        max_length=10,
                    ),
                ),
                ("message", models.TextField(help_text="대화 내용")),
                (
                    "sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="RAG 참조 소스 [{title, url, similarity}]",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="learning.aichatsession",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="연결된 강좌명 (없으면 커스텀 커리큘럼)",
                        max_length=200,
                    ),
                ),
                ("title", models.CharField(default="나의 학습 경로", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "학습 중"),
                            ("COMPLETED", "완료"),
                            ("DROPPED", "중단"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                (
                    "target_date",
                    models.DateField(blank=True, help_text="목표 완료일", null=True),
                ),
                (
                    "progress_percent",
                    models.IntegerField(default=0, help_text="전체 진도율 (0~100)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curricula",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="항목 제목", max_length=200)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "강의"),
                            ("QUIZ", "퀴즈"),
                            ("PROJECT", "프로젝트"),
                            ("REVIEW", "복습"),
                            ("SUPPLEMENT", "보충 학습"),
                        ],
                        default="LECTURE",
                        max_length=15,
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(
                        default=0, help_text="동적으로 조절 가능한 순서"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "is_supplementary",
                    models.BooleanField(
                        default=False, help_text="리라우팅으로 추가된 보충 항목인지"
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="learning.curriculum",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        blank=True,
                        help_text="연결된 강의",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="curriculum_items",
                        to="learning.lecture",
                    ),
                ),
            ],
            options={
                "ordering": ["order_index"],
            },
        ),
        migrations.CreateModel(
            name="ReroutingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("QUIZ_FAIL", "퀴즈 낙제"),
                            ("SLOW_PROGRESS", "진도 지연"),
                            ("LOW_UNDERSTANDING", "이해도 부족"),
                            ("SKILL_GAP", "스킬 갭 감지"),
                            ("STUDENT_REQUEST", "학생 요청"),
                            ("INSTRUCTOR_ADJUST", "강사 조정"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(
                        blank=True,
                        help_text="상세 사유 (예: Quiz #3 40점, 배열 메서드 이해 부족)",
                    ),
                ),
                (
                    "old_path",
                    models.JSONField(default=list, help_text="변경 전 Lecture IDs"),
                ),
                (
                    "new_path",
                    models.JSONField(
                        default=list, help_text="변경 후 Lecture IDs (보충 포함)"
                    ),
                ),
                (
                    "items_added",
                    models.IntegerField(default=0, help_text="추가된 항목 수"),
                ),
                (
                    "items_removed",
                    models.IntegerField(default=0, help_text="제거된 항목 수"),
                ),
                (
                    "ai_recommendation",
                    models.TextField(blank=True, help_text="AI의 리라우팅 근거 설명"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "curriculum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rerouting_logs",
                        to="learning.curriculum",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
