# Generated by Django 5.2.10 on 2026-02-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0033_aichatsession_aichatmessage_curriculum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_content", models.TextField(help_text="AI 요약 노트")),
                (
                    "key_concepts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="추출된 핵심 키워드 (예: ['클로저', 'this 바인딩', '프로토타입'])",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="learning.lecture",
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="요약 생성에 사용된 세션",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lecture_notes",
                        to="learning.learningsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
