# Generated by Django 5.2.10 on 2026-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0034_lecturenote"),
    ]

    operations = [
        migrations.AddField(
            model_name="sttlog",
            name="speaker",
            field=models.CharField(
                choices=[
                    ("INSTRUCTOR", "교수자"),
                    ("STUDENT", "학생"),
                    ("UNKNOWN", "미분류"),
                ],
                default="UNKNOWN",
                help_text="화자 구분",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sttlog",
            name="video_offset",
            field=models.FloatField(
                blank=True, help_text="영상 시작 시점 기준 경과 시간(초)", null=True
            ),
        ),
    ]
