# Generated by Django 5.2.10 on 2026-03-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0035_add_speaker_and_video_offset_to_sttlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="syllabus_file",
            field=models.FileField(
                blank=True,
                help_text="강의 계획서 파일 (PDF, HWP, DOCX)",
                null=True,
                upload_to="syllabus_files/",
            ),
        ),
    ]
