# Generated by Django 5.2.10 on 2026-03-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0036_add_syllabus_file_to_lecture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lecture",
            name="syllabus_file",
        ),
        migrations.AddField(
            model_name="learningsession",
            name="ai_status",
            field=models.CharField(
                default="PENDING", help_text="AI 처리 상태", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="learningsession",
            name="is_analyzing",
            field=models.BooleanField(default=False, help_text="분석 진행 중 여부"),
        ),
        migrations.AddField(
            model_name="learningsession",
            name="processing_error",
            field=models.TextField(blank=True, help_text="에러 로그", null=True),
        ),
        migrations.AddField(
            model_name="learningsession",
            name="script_segments",
            field=models.JSONField(default=list, help_text="분할된 스크립트 데이터"),
        ),
        migrations.AddField(
            model_name="syllabus",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="강의 자료 첨부 파일",
                null=True,
                upload_to="syllabus_files/",
            ),
        ),
    ]
