# Generated by Django 4.2.28 on 2026-03-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0037_add_syllabus_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningsession",
            name="user_note",
            field=models.TextField(
                blank=True, default="", help_text="사용자 개인 메모"
            ),
        ),
    ]
