# Generated by Django 5.2.10 on 2026-03-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0038_add_user_note_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="category",
            field=models.CharField(
                choices=[
                    ("IT_FRONTEND", "IT - 프론트엔드"),
                    ("IT_BACKEND", "IT - 백엔드"),
                    ("IT_DB", "IT - DB/ORM/캐시"),
                    ("IT_DEVOPS", "IT - 인프라/DevOps"),
                    ("IT_TESTING", "IT - 테스팅"),
                    ("IT_RUNTIME", "IT - 런타임"),
                    ("IT_BUILD", "IT - 빌드도구/CSS"),
                    ("IT_SECURITY", "IT - 보안"),
                    ("IT_BAAS", "IT - BaaS"),
                    ("IT_GENERAL", "IT - 종합"),
                    ("EDU_THEORY", "교육공학 - 학습이론"),
                    ("EDU_DESIGN", "교육공학 - 교수설계"),
                    ("EDU_TECH", "교육공학 - 에듀테크"),
                    ("EDU_ASSESS", "교육공학 - 교육평가"),
                    ("EDU_AI", "교육공학 - AI in Education"),
                    ("EDU_LEARN_SCI", "교육공학 - 학습과학"),
                    ("EDU_METHOD", "교육공학 - 교수학습방법"),
                    ("EDU_GENERAL", "교육공학 - 종합"),
                    ("OTHER", "기타"),
                ],
                default="OTHER",
                help_text="강의 분야 카테고리",
                max_length=20,
            ),
        ),
    ]
