# Generated by Django 5.2.10 on 2026-02-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("day_sequence", models.IntegerField(help_text="1일차, 2일차...")),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["day_sequence"],
            },
        ),
    ]
