# Generated by Django 5.2.10 on 2026-02-24 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="강좌명", max_length=200)),
                ("description", models.TextField(blank=True, help_text="강좌 설명")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FRONTEND", "프론트엔드"),
                            ("BACKEND", "백엔드"),
                            ("FULLSTACK", "풀스택"),
                            ("DATA", "데이터/AI"),
                            ("DEVOPS", "DevOps"),
                            ("MOBILE", "모바일"),
                            ("OTHER", "기타"),
                        ],
                        default="FULLSTACK",
                        help_text="카테고리",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="활성 여부")),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, default="", help_text="썸네일 이미지 URL"
                    ),
                ),
                (
                    "estimated_weeks",
                    models.IntegerField(default=12, help_text="예상 학습 기간 (주)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        help_text="강사",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="coursesection",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="소속 강좌",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="courses.course",
            ),
        ),
    ]
