# Generated by Django 5.2.10 on 2026-02-05 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "portfolio_type",
                    models.CharField(
                        choices=[
                            ("JOB", "취업용 포트폴리오 (Job Portfolio)"),
                            ("STARTUP", "창업용 MVP 기획서 (Startup MVP Spec)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "title",
                    models.CharField(default="자동 생성된 포트폴리오", max_length=200),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Markdown 형식의 생성된 포트폴리오 내용"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
