# Generated by Django 4.2.28 on 2026-02-10 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persona",
                    models.CharField(
                        choices=[
                            ("TECH_LEAD", "깐깐한 기술 팀장"),
                            ("FRIENDLY_SENIOR", "친절한 사수"),
                            ("HR_MANAGER", "인사 담당자"),
                            ("STARTUP_CEO", "스타트업 대표"),
                            ("BIG_TECH", "글로벌 빅테크 면접관"),
                            ("PRESSURE", "압박 면접관"),
                        ],
                        default="TECH_LEAD",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "면접 진행 중"),
                            ("COMPLETED", "종료됨"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews",
                        to="career.portfolio",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(help_text="AI 질문")),
                ("answer", models.TextField(blank=True, help_text="사용자 답변")),
                (
                    "feedback",
                    models.TextField(blank=True, help_text="AI 피드백 및 평가"),
                ),
                (
                    "score",
                    models.IntegerField(default=0, help_text="답변 점수 (0~100)"),
                ),
                ("order", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanges",
                        to="career.mockinterview",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
