# Generated by Django 5.2.10 on 2026-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0002_mockinterview_interviewexchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterview",
            name="max_minutes",
            field=models.IntegerField(
                blank=True, help_text="최대 면접 시간(분) (null이면 무제한)", null=True
            ),
        ),
        migrations.AddField(
            model_name="mockinterview",
            name="max_questions",
            field=models.IntegerField(
                blank=True, help_text="최대 질문 수 (null이면 무제한)", null=True
            ),
        ),
    ]
