# Generated by Django 5.2.10 on 2026-02-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0003_mockinterview_max_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockinterview",
            name="report_data",
            field=models.TextField(
                blank=True, default="", help_text="면접 결과 리포트 JSON"
            ),
        ),
    ]
