# Generated by Django 5.2.10 on 2026-02-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0004_mockinterview_report_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="페르소나 이름 (e.g. 까칠한 CTO)", max_length=100
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("TECH_LEAD", "기술 팀장"),
                            ("HR", "인사 담당자"),
                            ("VC", "벤처 캐피탈리스트"),
                            ("PEER", "동료 개발자"),
                            ("CUSTOMER", "고객"),
                            ("STARTUP_CEO", "스타트업 대표"),
                            ("BIG_TECH", "빅테크 면접관"),
                        ],
                        default="TECH_LEAD",
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="AI 페르소나 정의 프롬프트"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "기본"),
                            ("NORMAL", "보통"),
                            ("HARD", "압박"),
                        ],
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "avatar_emoji",
                    models.CharField(
                        default="🤖", help_text="아바타 이모지", max_length=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["role", "difficulty"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skill_block_id",
                    models.IntegerField(
                        blank=True,
                        help_text="관련 스킬블록 ID (learning.SkillBlock)",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="프로젝트/기능 명", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="프로젝트 설명"),
                ),
                (
                    "tech_stack",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="사용 기술 (예: ['React', 'Django', 'PostgreSQL'])",
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        blank=True, default="", help_text="GitHub 리포지토리 URL"
                    ),
                ),
                (
                    "demo_url",
                    models.URLField(blank=True, default="", help_text="데모/배포 URL"),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="담당 역할 (예: 프론트엔드 개발)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="career.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
