# Generated by Django 4.2.28 on 2026-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0005_interviewpersona_portfolioproject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mockinterview",
            name="persona",
            field=models.CharField(
                choices=[
                    ("TECH_LEAD", "깐깐한 기술 팀장"),
                    ("FRIENDLY_SENIOR", "친절한 사수"),
                    ("HR_MANAGER", "인사 담당자"),
                    ("STARTUP_CEO", "스타트업 대표"),
                    ("BIG_TECH", "글로벌 빅테크 면접관"),
                    ("PRESSURE", "압박 면접관"),
                    ("GROWTH", "성장 잠재력 평가관"),
                    ("PEER", "동료 개발자"),
                ],
                default="TECH_LEAD",
                max_length=20,
            ),
        ),
    ]
