# Generated by Django 5.2.10 on 2026-02-24 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "career_goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("JOB_SEEKER", "취업 준비"),
                            ("ENTREPRENEUR", "창업 준비"),
                            ("SKILL_UP", "역량 강화"),
                            ("CAREER_CHANGE", "직무 전환"),
                        ],
                        default="",
                        help_text="커리어 목표",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_tech_stack",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="관심 기술 스택 (예: ['React', 'Django', 'Docker'])",
                    ),
                ),
                (
                    "learning_style",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="학습 스타일 (예: visual, auditory, reading, kinesthetic)",
                        max_length=50,
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="기타 학습 설정 (알림, 난이도 선호도 등)",
                    ),
                ),
                ("bio", models.TextField(blank=True, default="", help_text="자기소개")),
                (
                    "github_url",
                    models.URLField(
                        blank=True, default="", help_text="GitHub 프로필 URL"
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, default="", help_text="포트폴리오 URL"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
